// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerDistorApi.Model;

#nullable disable

namespace ServerDistorApi.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20260325115645_AddQueryIndexes")]
    partial class AddQueryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("ServerDistorApi.Model.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AutoReleaseAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReadyAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RentedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AutoReleaseAtUtc");

                    b.HasIndex("ReadyAfterUtc");

                    b.HasIndex("ServerId");

                    b.HasIndex("Status");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("ServerDistorApi.Model.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreCPU")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HardwareGB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RentByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RentEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RentStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartRequestTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("ServerDistorApi.Model.ServerLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RentEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RentStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WasAutoReleased")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RentEnd");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
